@if ($errors->any())<div class="mb-4 rounded bg-red-100 p-3 text-black"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form action="{{ $action }}" method="POST" class="space-y-4">@csrf @if ($method !== 'POST') @method($method) @endif
    <div><label for="name" class="mb-1 block font-medium">Nama</label><input id="name" name="name" value="{{ old('name', $product?->name) }}" required class="w-full rounded border-gray-300"></div>
    <div><label for="slug" class="mb-1 block font-medium">Slug</label><input id="slug" name="slug" value="{{ old('slug', $product?->slug) }}" required class="w-full rounded border-gray-300"></div>
    <div><label for="description" class="mb-1 block font-medium">Deskripsi</label><textarea id="description" name="description" required class="w-full rounded border-gray-300">{{ old('description', $product?->description) }}</textarea></div>
    <div><label for="product_category_id" class="mb-1 block font-medium">Kategori</label><select id="product_category_id" name="product_category_id" required class="w-full rounded border-gray-300"><option value="">Pilih kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(old('product_category_id', $product?->product_category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="grid grid-cols-2 gap-4"><div><label for="stock" class="mb-1 block font-medium">Stok</label><input id="stock" type="number" min="0" name="stock" value="{{ old('stock', $product?->stock) }}" required class="w-full rounded border-gray-300"></div><div><label for="price" class="mb-1 block font-medium">Harga</label><input id="price" type="number" min="0" name="price" value="{{ old('price', $product?->price) }}" required class="w-full rounded border-gray-300"></div></div>
    <div><label for="image" class="mb-1 block font-medium">Gambar (path atau URL)</label><input id="image" name="image" value="{{ old('image', $product?->image) }}" required class="w-full rounded border-gray-300"></div>
    <div class="flex gap-3"><button class="rounded bg-red-600 px-4 py-2 font-semibold text-black hover:bg-red-700">Simpan</button><a href="{{ route('products.index') }}" class="rounded border border-gray-300 px-4 py-2 text-black">Batal</a></div>
</form>