@if ($errors->any())
    <div class="mb-6 flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">
        <span class="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-red-600 font-bold text-white">!</span>
        <div><p class="font-bold">Periksa kembali isian Anda</p><ul class="mt-1 list-inside list-disc text-red-700">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
    </div>
@endif
<form action="{{ $action }}" method="POST" enctype="multipart/form-data" class="space-y-6">@csrf @if ($method !== 'POST') @method($method) @endif
    <div class="grid gap-6 md:grid-cols-2"><div class="space-y-2"><label for="name" class="block text-sm font-bold text-slate-800">Nama produk <span class="text-red-600">*</span></label><input id="name" name="name" value="{{ old('name', $product?->name) }}" required placeholder="Contoh: Wireless Headphone" class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100"></div>
    <div class="space-y-2"><label for="slug" class="block text-sm font-bold text-slate-800">Slug <span class="text-red-600">*</span></label><input id="slug" name="slug" value="{{ old('slug', $product?->slug) }}" required placeholder="wireless-headphone" class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100"></div></div>
    <div class="space-y-2"><label for="description" class="block text-sm font-bold text-slate-800">Deskripsi <span class="text-red-600">*</span></label><textarea id="description" name="description" rows="5" required placeholder="Ceritakan keunggulan produk ini..." class="w-full resize-y rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100">{{ old('description', $product?->description) }}</textarea></div>
    <div class="space-y-2"><label for="product_category_id" class="block text-sm font-bold text-slate-800">Kategori <span class="text-red-600">*</span></label><select id="product_category_id" name="product_category_id" required class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100"><option value="">Pilih kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(old('product_category_id', $product?->product_category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="grid gap-6 sm:grid-cols-2"><div class="space-y-2"><label for="stock" class="block text-sm font-bold text-slate-800">Stok <span class="text-red-600">*</span></label><input id="stock" type="number" min="0" name="stock" value="{{ old('stock', $product?->stock) }}" required placeholder="0" class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100"></div><div class="space-y-2"><label for="price" class="block text-sm font-bold text-slate-800">Harga (Rp) <span class="text-red-600">*</span></label><input id="price" type="number" min="0" name="price" value="{{ old('price', $product?->price) }}" required placeholder="0" class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 shadow-sm outline-none transition focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100"></div></div>
    <div class="space-y-3"><label for="image" class="block text-sm font-bold text-slate-800">Gambar produk @if (!$product)<span class="text-red-600">*</span>@endif</label>@if ($product?->image)<div class="flex items-center gap-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><img src="{{ asset($product->image) }}" alt="{{ $product->name }}" class="h-16 w-16 rounded-lg object-cover"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Gambar saat ini</p><p class="mt-1 text-sm text-slate-700">Pilih file baru untuk menggantinya.</p></div></div>@endif<input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" @required(!$product) class="block w-full cursor-pointer rounded-xl border border-dashed border-slate-300 bg-slate-50 text-sm text-slate-600 file:mr-4 file:border-0 file:bg-red-600 file:px-5 file:py-3 file:font-bold file:text-white hover:border-red-400 hover:bg-red-50"><p class="text-xs text-slate-500">Format JPG, PNG, atau WEBP. Maksimal 2 MB.</p></div>
    <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('products.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-bold text-slate-600 transition hover:border-slate-300 hover:bg-slate-50">Batal</a><button type="submit" class="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-red-200 transition hover:bg-red-700 hover:shadow-red-300">Simpan produk</button></div>
</form>